### ISSUE TITLE
Myv spell checker does not work in LibreOffice

### ISSUE THREAD

**Issue by rueter** [divvun/divvunspell-libreoffice#7] opened 2023-02-10 06:42 UTC
I use Mac M2 Ventura.
I have proofread myv text in both .txt and .docx format.
I can define language for entire document as myv.

But:
I am unable to use nuvviDspeller to access version, anymore.
No word forms are underlined, even the XML tag names
<img width="1091" alt="myv_speller2023_02_10_libreoffice_no_version_no_misspellings" src="https://user-images.githubusercontent.com/14276164/218022541-12c35907-092e-44d8-8131-6c7d85c9996b.png">

.

This is a recent development, because I was able to document problems with full stops in issue https://github.com/divvun/divvunspell-libreoffice/issues/2

**Comment by snomos** [comment] 2023-02-10 06:55
Duplicate of #4.

**Closed as completed by snomos** 2023-02-10 06:55 UTC
Labels: duplicate
