### ISSUE TITLE
Lut speller does not work in LibreOffice

### ISSUE THREAD

**Issue by rueter** [divvun/divvunspell-libreoffice#8] opened 2023-02-10 06:49 UTC
I use Mac M2 Ventura.
I have proofread myv text in both .txt and .docx format.
I can define language for entire document as lut.

But:
I am unable to use nuvviDspeller to access version, anymore.
No word forms are underlined, even the XML tag names
<img width="1091" alt="lut_speller2023_02_10_not_work_in_libreoffice" src="https://user-images.githubusercontent.com/14276164/218022345-969845ca-db60-4efc-9c0d-0f636d7290eb.png">

This is a recent development, because I was able to document problems with full stops in issue https://github.com/divvun/divvunspell-libreoffice/issues/2

**Comment by snomos** [comment] 2023-02-10 06:54
Duplicate of #4.

**Closed as completed by snomos** 2023-02-10 06:54 UTC
Labels: duplicate
